import httpx
import pytest

from app.transcripts.errors import TranscriptError
from app.transcripts.providers.youtube_transcript_ai import YoutubeTranscriptAiProvider, parse_markdown

from .conftest import fixture_text, mock_client


def test_parse_real_auto_captions():
    t = parse_markdown(fixture_text("yta_SwpW4rEzNGM.txt"), "SwpW4rEzNGM", "youtube_transcript_ai")
    assert t.title.startswith("A Little Something Special")
    assert t.language == "en" and t.duration == 870
    assert t.available_languages == ["en"]
    assert t.segments[0].start == 3 and t.segments[0].text.startswith("oh helloo")
    assert all(s.approximate for s in t.segments)
    starts = [s.start for s in t.segments]
    assert starts == sorted(starts)
    assert all(a.end == b.start for a, b in zip(t.segments, t.segments[1:]))
    assert t.segments[-1].end == 870
    # абзац [0:33] начинается ровно на своей метке
    assert any(s.start == 33 for s in t.segments)
    assert "Generated by" not in t.segments[-1].text
    # HTML-сущности раскодированы
    assert not any("&nbsp;" in s.text or "\xa0" in s.text for s in t.segments)
    assert any("[ __ ]" in s.text for s in t.segments)


def test_parse_real_manual_with_languages():
    t = parse_markdown(fixture_text("yta_dQw4w9WgXcQ_de-DE.txt"), "dQw4w9WgXcQ", "youtube_transcript_ai")
    assert t.language == "de-DE" and t.duration == 207
    assert t.available_languages == ["de-DE", "en", "a-en", "ja", "pt-BR", "es-419"]
    assert t.segments[0].start == 18 and t.segments[0].text.startswith("Uns beiden")


async def _fetch(handler, lang=None):
    p = YoutubeTranscriptAiProvider(None, mock_client(handler))
    return await p.fetch("dQw4w9WgXcQ", lang)


async def test_fetch_passes_lang():
    seen = {}

    def handler(req: httpx.Request):
        seen["url"] = str(req.url)
        return httpx.Response(200, text=fixture_text("yta_dQw4w9WgXcQ.txt"))

    t = await _fetch(handler, "de-DE")
    assert seen["url"] == "https://youtube-transcript.ai/transcript/dQw4w9WgXcQ.txt?lang=de-DE"
    assert t.provider_id == "youtube_transcript_ai"


async def test_not_found_real_body():
    with pytest.raises(TranscriptError) as e:
        await _fetch(lambda r: httpx.Response(404, text=fixture_text("yta_not_found.txt")))
    assert e.value.code == "not_found" and "unavailable" in e.value.message


async def test_rate_limit_marker():
    # Синтетика: реальный текст лимита не сохранён, проверяем только маркер из PLAN.md
    body = "Looks like you're calling this API at high volume. Please slow down."
    with pytest.raises(TranscriptError) as e:
        await _fetch(lambda r: httpx.Response(200, text=body))
    assert e.value.code == "rate_limited"


async def test_http_429_and_network():
    with pytest.raises(TranscriptError) as e:
        await _fetch(lambda r: httpx.Response(429, text="slow down"))
    assert e.value.code == "rate_limited"

    def boom(req):
        raise httpx.ConnectError("down", request=req)

    with pytest.raises(TranscriptError) as e:
        await _fetch(boom)
    assert e.value.code == "network"


async def test_no_captions_real_body():
    # реальный ответ: HTTP 200, «# No captions available»
    with pytest.raises(TranscriptError) as e:
        await _fetch(lambda r: httpx.Response(200, text=fixture_text("yta_no_captions.txt")))
    assert e.value.code == "no_captions" and "нет субтитров" in e.value.message
