"""youtube-transcript.ai — без ключа, ответ markdown.

Формат (сверено с реальными ответами, фикстуры в tests/fixtures/yta_*.txt):
    # Transcript: <title>
    Language: en (auto-generated) · Duration: 14:30 · Words: 6215
    Other available languages: a-en (en) [auto], de-DE (de-DE), ...
    ## Transcript
    [0:03] абзац...
    <пустая строка>
    [0:33] абзац...
    ---
Время есть только у абзацев → сегменты approximate.
"""

from __future__ import annotations

import html
import json
import re

from app.transcripts.base import TranscriptProvider
from app.transcripts.models import Transcript, TranscriptSegment
from app.transcripts.normalize import fill_ends, parse_clock, split_paragraph

BASE_URL = "https://youtube-transcript.ai/transcript"
RATE_LIMIT_MARKER = "calling this api at high volume"

_PARA = re.compile(r"^\[(\d+(?::\d{1,2}){1,2})\]\s*(.*)$")
_LANG_LINE = re.compile(r"^Language:\s*(.+)$", re.M)
_OTHER = re.compile(r"^Other available languages:\s*(.+)$", re.M)
_TITLE = re.compile(r"^# Transcript:\s*(.+)$", re.M)
_REASON = re.compile(r"^Reason:\s*(.+)$", re.M)


class YoutubeTranscriptAiProvider(TranscriptProvider):
    id = "youtube_transcript_ai"
    name = "youtube-transcript.ai"
    docs_url = "https://youtube-transcript.ai/youtube-transcript-api"
    pricing = "Бесплатно, без ключа; fair-use лимит. Время внутри абзацев приблизительное (≈)."

    async def fetch(self, video_id: str, language: str | None, api_key: str | None = None) -> Transcript:
        params = {"lang": language} if language else None
        r = await self.request("GET", f"{BASE_URL}/{video_id}.txt", params=params)
        body = r.text
        if RATE_LIMIT_MARKER in body.lower():
            raise self.error("rate_limited", f"{self.name}: превышен fair-use лимит", r.status_code)
        if body.lstrip().startswith("# No captions available"):
            # 200 + markdown без транскрипта: у видео на YouTube нет субтитров (даже авто)
            raise self.error("no_captions", "У этого видео на YouTube нет субтитров (даже автоматических)", r.status_code)
        if r.status_code == 404 or body.lstrip().startswith("# Transcript unavailable"):
            raise self._unavailable(body, r.status_code)
        if r.status_code >= 400:
            raise self.http_error(r)
        return parse_markdown(body, video_id, self.id)

    def _unavailable(self, body: str, status: int):
        m = _REASON.search(body)
        reason = m.group(1).strip() if m else "transcript unavailable"
        try:
            reason = json.loads(reason).get("error", reason)
        except (ValueError, AttributeError):
            pass
        low = reason.lower()
        code = "no_captions" if ("transcript" in low or "caption" in low or "subtitle" in low) else "not_found"
        return self.error(code, f"{self.name}: {reason}", status)


def _parse_header(body: str) -> tuple[str | None, str | None, float | None, list[str]]:
    title = (m.group(1).strip() if (m := _TITLE.search(body)) else None)
    language, duration = None, None
    if m := _LANG_LINE.search(body):
        for field in m.group(1).split("·"):
            field = field.strip()
            if field.lower().startswith("duration:"):
                try:
                    duration = parse_clock(field.split(":", 1)[1])
                except ValueError:
                    pass
            elif language is None and not field.lower().startswith("words:"):
                language = field.split()[0]
    langs = [language] if language else []
    if m := _OTHER.search(body):
        for item in m.group(1).split(","):
            code = item.strip().split(" ")[0]
            if code and code not in langs:
                langs.append(code)
    return title, language, duration, langs


def parse_markdown(body: str, video_id: str, provider_id: str) -> Transcript:
    from app.transcripts.errors import TranscriptError

    title, language, duration, langs = _parse_header(body)
    _, sep, rest = body.partition("## Transcript")
    if not sep:
        raise TranscriptError("parse", "youtube-transcript.ai: нет раздела '## Transcript'", provider_id)

    paragraphs: list[tuple[float, str]] = []
    for line in rest.splitlines():
        line = line.strip()
        if line.startswith("---") or line.startswith("Generated by"):
            break
        if m := _PARA.match(line):
            # провайдер оставляет HTML-сущности: «[&nbsp;__&nbsp;]» (запиканный мат) → «[ __ ]»
            paragraphs.append((parse_clock(m.group(1)), html.unescape(m.group(2)).replace("\xa0", " ").strip()))
        elif line and paragraphs:  # перенос абзаца на следующую строку
            t, txt = paragraphs[-1]
            paragraphs[-1] = (t, f"{txt} {html.unescape(line).replace(chr(0xA0), ' ')}")
    if not paragraphs:
        raise TranscriptError("no_captions", "youtube-transcript.ai: пустой транскрипт", provider_id)

    segments: list[TranscriptSegment] = []
    for i, (start, text) in enumerate(paragraphs):
        end = paragraphs[i + 1][0] if i + 1 < len(paragraphs) else (duration or start + 30)
        segments.extend(split_paragraph(start, max(end, start), text))
    return Transcript(
        video_id=video_id, language=language or "und", title=title, duration=duration,
        available_languages=langs, provider_id=provider_id, segments=fill_ends(segments, duration),
    )
